# Spring properties
spring:
  application:
    name: public-api  # Identify this application

# Map the error path to error template (for Thymeleaf)
error:
  path=/error

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port

logging:
  level:
    org.springframework.web: TRACE